### ISSUE TITLE
Discover a gradle/maven workspace

### ISSUE THREAD

**Issue by ikezedev** [kotlin-analyzer/kotlin-analyzer#6]

**Comment by iambenkay** [comment]
For discovering gradle, I am considering the following checks:
- `build.gradle` exists in root

For Maven:
- `pom.xml` exists in root

Any other recommendations @ikezedev ?

**Comment by iambenkay** [comment]
Using information from [https://start.spring.io/](https://start.spring.io/), I have been able to extract important markers for deciphering the workspace type.
```rs
fn detect_workspace_type(workspace_root: &PathBuf) -> Option<WorkspaceType> {
    if workspace_root.join("pom.xml").exists() {
        return Some(WorkspaceType::Maven);
    } else if workspace_root.join("build.gradle").exists()
        || workspace_root.join("build.gradle.kts").exists()
    {
        return Some(WorkspaceType::Gradle);
    }

    None
}
```
